spring.application.name=social-media-backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=social_media;encrypt=true;trustServerCertificate=true
spring.datasource.username=social_media_app
spring.datasource.password=SocialMedia@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=never